<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>bzp</name>
  <uuid>71665ce9-db76-4008-a214-cacc6201234e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the estimated cost of Request is more than 30000 and at most 140000
	and the destination of Request is BZP 
	and the repeat count of Request is at most 2
then
    set the status of decision to ACCEPTED; 
else
	set the status of decision to REJECTED ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
