<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>copy to output</name>
  <uuid>e538c2ae-74ad-46f2-a5c6-e5de34022a9c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Publication Request where 
		the status is REJECTED, 
		the destination is the destination of Request , 
		the estimated cost is the estimated cost of Request , 
		the order type is the order type of Request , 
		the repeat count is the repeat count of Request;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
