<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>freehand</name>
  <uuid>73fb811c-902a-462b-bea6-d87283204760</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the estimated cost of Request ≤ 30000 and the destination of Request is WEBSITE
then set the status of decision to ACCEPTED;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
