<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ted</name>
  <uuid>c667f8af-0440-48db-b90a-15e48facf730</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the estimated cost of Request ≥ 140000 and the destination of Request is TED
and the repeat count of Request ≤ 2 
then set the status of decision to ACCEPTED ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
