<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>works</name>
  <uuid>aea9b368-a828-4452-a94d-34494d586505</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the order type of Request is WORKS
then set the status of decision to FORWARDED; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
